name: Deploy práctica

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write        # deja que GitHub emita el token de identidad para OIDC
  contents: read

jobs:
  build:
    name: Validar el sitio
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Verificar que existe index.html
        run: |
          test -f index.html && echo "index.html encontrado, todo bien"

  deploy:
    name: Desplegar a S3
    needs: build           # solo corre si 'build' salió verde
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}    # vacío por ahora -> aquí fallará
          aws-region: us-east-1

      - name: Subir el sitio a S3
        run: aws s3 sync . s3://${{ secrets.S3_BUCKET }} --exclude ".git/*" --exclude ".github/*"
